### ISSUE TITLE
Unable to configure apollo extension

### ISSUE THREAD

**Issue by mklemarczyk** [apollographql/vscode-graphql#187]
Hello, I got the last update 2.2.0 and it does not work anymore for my project.

I use the vs code workspace and my apollo config file is in the root folder. I use nx workspace folder structure fo angular project, that means the folder structure is quite deep.

I can provide more details later in the afternoon. Error is written to the console that it does not find the configuration file, even if you open the configuration file. I couldn’t find any helpful information in the verbose logs of the extension.

Last extension version that works for me is 1.20.0. I use apollo client npm in version 3.11.2 and apollo-angular in version 7.0.2.

Any version of extension 2.x has the same issue. I seen that your extension has very low reputation at VS Code Marketplace.

**Comment by phryneas** [comment]
Hi Maciej,

it would be great if you could share the name & contents of your configuration file (of course without sensitive details), an idea of your folder layout (where is the config file, which folder do you have open), and the exact error message.
I'll look into it as soon as I have more information :)

**Comment by bhpark1013** [comment]
```
module.exports = {
  client: {
    service: {
      localSchemaFile: './schema.gql',
    },
  },
  exclude: ['**/*.e2e-spec.ts'],
};

```
I am also having similar experience. I haven't try earlier version cause i have some files to exclude(which seems not working option on version 1.x). I am trying to link with local schema without using Apollo schema registry. 

I have logs which seems not that helpful
```
.vscode/extensions/apollographql.vscode-apollo-2.2.0/lib/language-server/server.js:1035
`)}t(Swn,"dedentBlockStringValue");function Ewn(a){le  //...and so on
[Error - 6:14:03 PM] Server process exited with code 1.
[Error - 6:14:03 PM] Client Apollo GraphQL: connection to server is erroring.
Channel closed
```
my apollo/server version is: "@apollo/server": 4.9.5,

Can i get any help?

**Comment by phryneas** [comment]
I'm going to do a bit of digging what code that points to.
Meanwhile: is this already from the "Apollo" output or is there maybe additional information there?
![image](https://github.com/user-attachments/assets/da8852da-4681-4a2a-a76d-7919c1d95f5c)

**Comment by phryneas** [comment]
@bhpark1013 also, could I please get the full unshortened error with the full stack trace? That might actually tell me something :)

**Comment by phryneas** [comment]
Assuming that this error comes somewhere out of the corner of code you are pointing to, it would come from `mergeTypeDefs` from `"@graphql-tools/merge"` - do you have anything special in your schema?

**Comment by mklemarczyk** [comment]
For the configuration we have:

```
// Configuration for the GraphQL-Apollo plugin for VS Code to verify the GraphQL documents with Topology Manager service.
module.exports = {
  client: {
    includes: ['./libs/data-access-services/api/src/lib/contracts/**/*.graphql'],
    service: {
      name: 'apis-manager',
      url: 'http://127.0.0.1:21160/apis/graphQL/',
      // optionally turn off SSL validation check
      skipSSLValidation: true
    }
  }
};

```

Configuration is located in root folder of nx workspace.
Example of folder structure : https://github.com/nrwl/nx-examples/tree/master

VS Code output logs
[apollo-graphql.log](https://github.com/user-attachments/files/17250105/apollo-graphql.log)

**Comment by phryneas** [comment]
@mklemarczyk 
Hmm, that looks like it's not crashing, but there's just not a lot happening...

Just to be sure: your server is running, and you also see an introspection query come in there?

PS: shouldn't make a difference, but for a http connection, you won't need `skipSSLValidation`.

**Comment by phryneas** [comment]
As for now, I suspect that your problems might come somewhere from these changes, but I can't put my finger on it :/

https://github.com/apollographql/vscode-graphql/pull/160/files#diff-d675ce2b91731f4d5c3cdb539cea2811a6c1c5bfebcc59b64e56b16db8471333

**Comment by phryneas** [comment]
Are you actually using `https` and just omitted that in the logs? It seems that switching from `isomorphic-fetch` to the node implementation with `undici` might have broken this line:

https://github.com/apollographql/vscode-graphql/blob/d760281ed41f6b37be3589db892b84fd3d55c06a/src/language-server/providers/schema/endpoint.ts#L34

Seems I might need to swap in a `dispatcher` there instead... :/

**Comment by phryneas** [comment]
If this is your problem, could you maybe check out if #190 fixes the problem for you? I have to go OOO right now, but I'll spend more time on this on monday.

**Comment by mklemarczyk** [comment]
Hello @phryneas our server is local HTTP server, without any security. That option you mentioned I think was a workaroud from long time ago, it works in old version (1.20.0) without it as well.

Yes there is IntrospectionQuery logged in server for both extension 1.20.0 and 2.2.0.
I did not tried your change from PR yet.

For any hover in graphql there is no result.
```
[Trace - 4:51:54 PM] Received response 'textDocument/hover - (13)' in 2ms.
No result returned.
```

**Comment by phryneas** [comment]
Could you try to execute the `Apollo: Show Status` command?

that would look something like 
```
------------------------------
🚀 Apollo GraphQL v2.2.0
------------------------------
✅ Service Loaded!
🆔 Service ID: localMultiSchema
🏷 Schema Tag: current
📈 Number of Types: 16 (0 client types)
------------------------------
```
and tell us if your schema could be loaded and how many types were recognized.

**Comment by mklemarczyk** [comment]
This is what I got in the logs
![image](https://github.com/user-attachments/assets/307deefe-5c5c-455b-86c6-b5b12e51b556)

Config (apollo.config.js) is located as it is written in logs that I provided and its content is as I send in previous messages. It works fine with 1.x but 2.x has some problems. :/

**Comment by phryneas** [comment]
@mklemarczyk Just to validate, you are getting that while you have an editor open with a file that was previously recognized?

This could be something with the `includes`/`excludes` then... I'll have to take a look. We updated a lot of dependencies going into 2.x

**Comment by mklemarczyk** [comment]
Yes, I confirm, for the same exact configuration file, no configuration done in VS Code what so ever (default extension settings).
I do not have includes/excludes defined in apollo configuration file defined. I assume you are talking about extensions code than.

**Comment by phryneas** [comment]
@mklemarczyk Didn't you have `includes` in this comment? https://github.com/apollographql/vscode-graphql/issues/187#issuecomment-2321227216

My assumption is that because we updated one of the dependencies (e.g. we jumped multiple major versions of `glob`), that doesn't match your files correctly anymore 🤔

**Comment by phryneas** [comment]
@mklemarczyk I've created this custom build that logs a bit more and should hopefully shed some light here.

---


[vscode-apollo-0.0.0-build.1725552078.pr.195.commit.e20f10b.zip](https://github.com/apollographql/vscode-graphql/actions/runs/10723970223/artifacts/1897164825).

To install the extension, download the file, unzip it and install it in VS Code by selecting "Install from VSIX..." in the Extensions view.

Alternatively, run
```sh
code --install-extension vscode-apollo-0.0.0-build.1725552078.pr.195.commit.e20f10b.vsix --force
```
from the command line.

---

Could you please try that out? No need to enable trace logging, this should show up in the Output panel even without that.

It should show us your `include` and `exclude` patterns, which of your files were successfully found, and if the schema is downloaded & extended correctly.

**Comment by Zache** [comment]
I'm also having this problem. Here is the output for me when running the special extension:

```
(node:7328) Warning: Setting the NODE_TLS_REJECT_UNAUTHORIZED environment variable to '0' makes TLS connections and HTTPS requests insecure by disabling certificate verification.
(Use `Code --trace-warnings ...` to show where the warning was created)
[INFO] intializing project with config file file:///<CORRECT PATH>/apollo.config.js
[INFO] includes: [src/graphql/**/*.graphql]
[INFO] excludes: [**/node_modules, **/__tests__]
[INFO] found files: 'ALL OF THE GRAPHQL'
[INFO] Loading schema for client project<OUR GRAPH ID>
[INFO] Adding client metadata to schema nodes
[INFO] Successfully handled schema
[INFO] Loading schema for client project<OUR GRAPH ID>
[INFO] Adding client metadata to schema nodes
[INFO] Successfully handled schema
------------------------------
🚀 Apollo GraphQL v0.0.0-build.1725552078.pr.195.commit.e20f10b
------------------------------
❌ Service stats could not be loaded. This may be because you're missing an apollo.config.js file or it is misconfigured. For more information about configuring Apollo projects, see the guide here (https://go.apollo.dev/t/config).
```

I redacted our graph id and parts of the paths, but those shouldn't be relevant.

**Comment by phryneas** [comment]
@Zache thank you for the report!
Just to be clear, you are executing the `Apollo: Show Status` command while your cursor is in an editor of one of the `.graphql` files that are listed under `[INFO] found files: `?

**Comment by Zache** [comment]
Unsure where my cursor was, but I have a GraphQL file (listed by the
extension in a redacted part) open. In case you meant the caret I also
don’t know where it was either. I’ll report back when I’m at my computer
again

**Comment by phryneas** [comment]
@Zache Yeah, that's quite important - the extension is only active inside of files in your `includes`, and that `"Show Status"` command will only give you the right feedback if your "active editor" has one of those files opened. I know it's a bit complex, but since we support multiple differently configured projects inside the same workspace (e.g. monorepos), we have to make that distinction.

**Comment by Zache** [comment]
@phryneas I tried it again, this time making sure that my cursor and caret was in an included .graphql file. But I still get the same error. Maybe it could be of interest that if I click the 🚀Apollo button down in the status bar it prints the extension name, but not the status error. I'm pretty certain that used to print the status also...

**Comment by phryneas** [comment]
@Zache That is really curious. 
I'll try a few more things tomorrow, but I have to admit that at this point I feel a bit lost - we have no real clues here.

If you have any more ideas what could make your environment unique, or could even come up with a minimal reproduction, I'd be very grateful.

**Comment by mklemarczyk** [comment]
Hello @phryneas I was not able to download the file you mentioned. I get 404 error.
https://github.com/apollographql/vscode-graphql/actions/runs/10723970223/artifacts/1897164825

In some free time I will record you a video with the issue later today.

**Comment by phryneas** [comment]
@mklemarczyk yeah that build only stays around for two weeks - here is a new one :)

---

You can download the latest build of the extension for this PR here:
[vscode-apollo-0.0.0-build-1726659863.pr-195.commit-a14272e.zip](https://github.com/apollographql/vscode-graphql/actions/runs/10921431901/artifacts/1947479881).

To install the extension, download the file, unzip it and install it in VS Code by selecting "Install from VSIX..." in the Extensions view.

Alternatively, run
```sh
code --install-extension vscode-apollo-0.0.0-build-1726659863.pr-195.commit-a14272e.vsix --force
```
from the command line.

**Comment by mklemarczyk** [comment]
![image](https://github.com/user-attachments/assets/9e56204a-f812-4409-9c2c-0fa315c81ddf)
This showed that error, did not load anything. 

The hidden parts are my username, and project folder name.

Those are other extensions that I use
![image](https://github.com/user-attachments/assets/8ff12c6e-35f7-4dea-ae3f-a696809a5a84)

**Comment by phryneas** [comment]
@mklemarczyk I believe you just found a bug that I shipped yesterday 😅 
There's a lot of work going on around "config file loading" because the ways that shipped with recent versions of `cosmiconfig` is unfortunately just not doing the things we want it to do anymore.

I just opened a PR to fix this bug over in #211 and will have a new build to try in a moment :)

**Comment by phryneas** [comment]
Okay, new build coming up - thank you for your patience!

---

You can download the latest build of the extension for this PR here:
[vscode-apollo-0.0.0-build-1726752845.pr-195.commit-2c7e56c.zip](https://github.com/apollographql/vscode-graphql/actions/runs/10942101632/artifacts/1953265014).

To install the extension, download the file, unzip it and install it in VS Code by selecting "Install from VSIX..." in the Extensions view.

Alternatively, run
```sh
code --install-extension vscode-apollo-0.0.0-build-1726752845.pr-195.commit-2c7e56c.vsix --force
```
from the command line.

**Comment by Zache** [comment]
Now I'm getting errors `The error was: ReferenceError: module is not defined in ES module scope`, but get around that. I also had a problem where we used `require` to get some dotenv code running, but I think I could remove that since the extension documentation says it can read from .env files. 

One thing I don't think I have mentioned is that I do get a little blue "play" button to open in Apollo Studio and that works without any problem. But I still don't get Intellisense

**Comment by phryneas** [comment]
@Zache those errors *should* have been solved with friday's release. Could you please verify that you are on `2.3.2`?

If you are still encountering, could you share some of the things in your config file that might help me reproduce the problem?

**Comment by ankitprahladsoni** [comment]
I'm still getting this issue on `2.3.2`. We use a shared config in our monorepo which we import in each project workspace separately.

Example code of `apollo.config.js`:
```
const sharedConfig = require('@path/to/shared/config');

module.exports = {
    ...sharedConfig,
    client: {
        ...sharedConfig.client,
        includes: [
          // workspace specific files
        ],
    },
};
```

Whenever I start VSCode, I get the below error
```
Error: A config file failed to load with options: {"configPath":"/path/to/workspace1"}.
    The error was: ReferenceError: require is not defined in ES module scope, you can use import instead
    at loadConfig (/Users/{username}/.vscode/extensions/apollographql.vscode-apollo-2.3.3/lib/language-server/server.js:840:1325)
    at async Promise.all (index 0)
    at async yDe.addProjectsInFolder (/Users/{username}/.vscode/extensions/apollographql.vscode-apollo-2.3.3/lib/language-server/server.js:1114:4075)
    at async Promise.all (index 0)
    at async /Users/{username}/.vscode/extensions/apollographql.vscode-apollo-2.3.3/lib/language-server/server.js:1114:7661
```
I've explained a bit about our setup in #83

**Comment by gusvargas** [comment]
I was also having the `A config file failed to load` issue. After switching to the JSON format (from CJS) the error changed into the `Client Apollo GraphQL: connection to server is erroring.` variety.

After forcing `2.0.0` of the extension, I got a much more useful (and accurate) error: `Error: ️️There are multiple definitions for the XXX operation.` Fixing the duplicate definition issue fixed the extension.

It seems like some change between `2.0.0` and the current version made it so that specific errors are getting masked by broader errors.

If anyone else is having this issue I'd suggest trying `2.0.0` to see if you get a more precise error.

![image](https://github.com/user-attachments/assets/0db484a8-cade-4bc6-9d5a-6f43f6d9a117)

**Comment by mklemarczyk** [comment]
Hello @phryneas I tired the last release 2.3.3 of the extension. It says now that config file cant be found. I see the request in server for the GraphQL meta, but nothing moves in Visual Studio Code.

I confirm that I do not have `The error was: ReferenceError: module is not defined in ES module scope` error anymore. At least I do not see it in output for Apollo GraphQL extension.

**Comment by phryneas** [comment]
I really really want to help y'all, but I really don't get this reproduced on my end. 😞 

I know that it is a big ask, but could one of you try to create some sort of reproduction for this?

**Comment by ankitprahladsoni** [comment]
Try this test repo https://github.com/ankitprahladsoni/vscode-graphql-187
No error is thrown on `v2.0.0`, but we see the above-mentioned error in  `v2.3.3`

**Comment by phryneas** [comment]
@ankitprahladsoni THANK YOU that helped a ton!

I believe I could fix what you are encountering there - could you please give this build a try? :)

 https://github.com/apollographql/vscode-graphql/pull/224#issuecomment-2399241389

I fear that @mklemarczyk might have a different problem though :/

**Comment by ankitprahladsoni** [comment]
Yes, that worked for me. Thanks for the super quick solution 🙇🏼

**Comment by phryneas** [comment]
We're in a code freeze this week, so just a heads up so you're not confused - this will be released next week :)

**Comment by phryneas** [comment]
@ankitprahladsoni I just released that fix!

**Comment by phryneas** [comment]
Another configuration loading bug in older VSCode versions has been fixed in #226 and will be released in a bit.

**Comment by hmz22** [comment]
Hello dear
I still have problem with new version i update plugin to 2.3.6
```
module.exports = {
  client: {
    service: {
      name: "msrt-froums",
      url: "http://localhost:4031/graphql",
    },
    excludes: ["src/graphql/__generated__/**", "src/graphql/**/*.generated.ts"],
  },
};

```
and this my config in `apollo.config.js` I use in node.js 14 get me this error on apollo status:
```
------------------------------
🚀 Apollo GraphQL v2.3.6
------------------------------
❌ Service stats could not be loaded. This may be because you're missing an apollo.config.js file or it is misconfigured. For more information about configuring Apollo projects, see the guide here (https://go.apollo.dev/t/config).
```
when downgrade to 1.20 everything worked

**Comment by phryneas** [comment]
@hmz22 could you try to recreate your exact folder layout with an otherwise empty project and upload that somewhere so I could take a look?

**Comment by hmz22** [comment]
> @hmz22 could you try to recreate your exact folder layout with an otherwise empty project and upload that somewhere so I could take a look?

I can't publish it in public because this is a private organization app and backend are microservices.

**Comment by phryneas** [comment]
@hmz22  I'm really talking about a minimal reporduction that shows the same behaviour - just a similar (mostly) empty folder structure, with the config file in the place where you have it and a `.js` or `.graphql` file in the place where you expect to get the extension features.

I defintely don't want access to the full project or any sensitive data! :)

**Comment by hmz22** [comment]
> @hmz22  I'm really talking about a minimal reporduction that shows the same behaviour - just a similar (mostly) empty folder structure, with the config file in the place where you have it and a `.js` or `.graphql` file in the place where you expect to get the extension features.
> 
> I defintely don't want access to the full project or any sensitive data! :)

Ok I create it and publish it.

**Comment by mklemarczyk** [comment]
[testing.zip](https://github.com/user-attachments/files/17542925/testing.zip)
Some example mono-repo created with nx, you can open it in vs code with MyTest file. It is intended way to work with this example.

List of all installed extensions
```
adamhartford.vscode-base64
angular.ng-template
apollographql.vscode-apollo
cake-build.cake-vscode
dbaeumer.vscode-eslint
eamodio.gitlens
editorconfig.editorconfig
esbenp.prettier-vscode
firsttris.vscode-jest-runner
graphql.vscode-graphql (disabled)
graphql.vscode-graphql-syntax (disabled)
jock.svg
johnstoncode.svn-scm
maziac.binary-file-viewer
mhutchie.git-graph
ms-azuretools.vscode-docker
ms-dotnettools.csharp
ms-dotnettools.vscode-dotnet-runtime
ms-edgedevtools.vscode-edge-devtools
ms-vscode-remote.remote-containers
ms-vscode-remote.remote-ssh
ms-vscode-remote.remote-ssh-edit
ms-vscode.hexeditor
ms-vscode.powershell
ms-vscode.remote-explorer
ms-vsliveshare.vsliveshare
msjsdiag.debugger-for-edge
nrwl.angular-console
pranaygp.vscode-css-peek
praneshpsg239.json-helper
pucelle.vscode-css-navigation
redhat.vscode-commons
redhat.vscode-xml
svipas.prettier-plus
wix.vscode-import-cost
```

I am sorry, I do not have much time at work for that issue. We started to evaluate alternative extensions in place of apollo graphql.

**Comment by HTMLhead** [comment]
@hmz22 @bhpark1013

Hello, I was facing the exact same issue as you. You might want to check if you have queries or mutations with identical names.

For example:
```javascript
// a.query.ts
const CREATE_SOMETHING = gql(`
  mutation createSomething($a: String!) {
    createSomething(a: $a)
  }
`);

// b.query.ts
const CREATE_SOMETHING = gql(`
  mutation createSomething($a: String!) {
    // This is the issue
    createSomething(a: $a)
  }
`);
```

Changing it to something like this solved the issue for me:

```javascript
// a.query.ts
const CREATE_SOMETHING = gql(`
  mutation createSomething($a: String!) {
    createSomething(a: $a)
  }
`);

// b.query.ts
const CREATE_SOMETHING = gql(`
  mutation createSomething_B($a: String!) {
    // Mutation name changed
    createSomething(a: $a)
  }
`);
```

I realized this after downgrading to version 2.0.0 and inspecting the error logs. After renaming the conflicting queries/mutations, everything worked correctly.

I hope this helps you.

**Comment by phryneas** [comment]
@mklemarczyk in this case, I unfortunately don't have an api running on that port, and as a result the configuration fails to load 😞 

As an alternative, could you try to set this setting and report back what you get in the logs?

![image](https://github.com/user-attachments/assets/c1b5dce0-2be7-4fce-bb3c-5d4e7ffb67a9)

**Comment by phryneas** [comment]
@HTMLhead so I understand you right that you did get that error in the old versions, but just nothing in the current versions?

**Comment by HTMLhead** [comment]
Hello @phryneas yes that's right.

**Comment by davyw** [comment]
Hello @phryneas,

I have the same issue where schema is loaded from my backend correctly and is valid but where the 
'Service stats could not be loaded' message appears in output pane.
It no longer works since v2.0.0, v1.20 does work.
I am no expert in vs code extensions, but took the liberty to clone the repo and tried to debug the extension using my own workspace to investigate what could be a root cause. 

Obviously, I have limited knowledge to the code base, but where it seems to go wrong
is with the way for example FileSet class is created, the rootURI seems wrong.
In method FileSet.includesFile for example normalizeURI(filePath) is used (ex. normalizeURI('file:///c%3a/project-path/src/test.ts') returns 'c:/project-path/src/test.ts'), seems correct, with forward slash unix style.
But the rootURI member of FileSet is not correct, rootURI.fsPath returns '\\project-path', no drive letter
and backslash (windows style).
Due to that fact workspace.projectForFile returns undefined and no project stats are found.

I tried playing around a bit by using normalizeURI() some more or URI.file(normalizeURI(..)) if needed, but cannot pinpoint the exact place where it goes wrong. 
I'm not sure this is a configuration setting that is wrong or path conversions that get mixed up in the language server, but I hope this information helps to find the issue.

**Comment by CassandraCat** [comment]
Same issue. When I use 2.0.0, it works fine

**Comment by mklemarczyk** [comment]
> @mklemarczyk in this case, I unfortunately don't have an api running on that port, and as a result the configuration fails to load 😞
> 
> As an alternative, could you try to set this setting and report back what you get in the logs?
> 
> ![image](https://private-user-images.githubusercontent.com/4282439/381597962-c1b5dce0-2be7-4fce-bb3c-5d4e7ffb67a9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI5MTc2OTksIm5iZiI6MTczMjkxNzM5OSwicGF0aCI6Ii80MjgyNDM5LzM4MTU5Nzk2Mi1jMWI1ZGNlMC0yYmU3LTRmY2UtYmIzYy01ZDRlN2ZmYjY3YTkucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTEyOSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDExMjlUMjE1NjM5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YzY3MDRmYzdhMDRhY2ZiNGY1NDk0M2Y1N2RmNDMxN2M0MzVhZDdiNzhlY2MyMzY4ZmY0ZTBiM2NlYzc4ZDIwOCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.S5dOr7y_xaGqOYL4_YKrWmx0-bzoNiPNZSdcroinxd8)

Sure I can provide logs, did you add some more messages ? Last time there were no helpful messages in logs.

**Comment by phryneas** [comment]
@davyw I'm sorry that I could get back to this just now, but your analysis is spot-on and I could reproduce it and believe I have a fix!

Could all windows users in this issue please try the build in #240 and see if that fixes the problems for them? @mklemarczyk  I think you're a windows user, too? :)

**Comment by davyw** [comment]
@phryneas No worries, busy times at the end of the year ;)

Downloaded the build from #240 installed it, now it is working as expected!
Thanks!

**Comment by phryneas** [comment]
That hotfix is now released as [2.4.0](https://github.com/apollographql/vscode-graphql/releases/tag/v2.4.0) - please let me know if this issue is finally resolved :)

**Comment by mklemarczyk** [comment]
I tried the version 2.5.2 and it solves my problem that I raised in this issue ticket. The code completion for grahQL works, the type inspection with tooltips works, refresh works and display correct message in output view.
![image](https://github.com/user-attachments/assets/89aa031c-2eca-458e-9b6b-e43d04730eec)

Side note : extension works correctly only if the GraphQL server was working when opening VSCode.
If server was not online / accessible, the action to refresh the GraphQL will still result in state where you cant work.
Workaround : restart your VSCode.
Context for image below : first print is from fact VSCode is started. After that I realized server was down so I started it. Second and third prints are from pressing Apollo extension button in VSCode "refresh button?".
![image](https://github.com/user-attachments/assets/49a1bf95-0fbc-46e3-a035-283535c9c1df)

Also use of this button is unclear (I always thought it was a refresh button to update with latest schema on the GraphQL server):
![image](https://github.com/user-attachments/assets/ebbb1336-cb90-4df9-91a8-5f44457e8630)
Could we have some more docs about what it does and when ? Does it need a graphql file open in VSCode ? Does it really refresh or just retry if initial load failed ? Or it is just an indicator that Apollo extensions exists ?
First press seems to print nice message, but subsequent runs do not produce much.

**Comment by phryneas** [comment]
@mklemarczyk I'm glad that we got the core to this issue solves.

As for the button: it's just an indicator that the extension is loaded (showing either loading, loaded or warning) - clicking it shows just statistics.

A reload functionality on there would honestly be a good idea 🤔 

Anyways, I think this issue is finally resolved and I'm closing this issue. Thank you for reporting in - it's a bit of a christmas present to have this off my mind :)

**Comment by dylanwulf** [comment]
> My assumption is that because we updated one of the dependencies (e.g. we jumped multiple major versions of glob), that doesn't match your files correctly anymore 🤔

This turned out to be exactly my problem. It looks like glob v8 removed support for backslashes (`\`) in path strings, so my existing config stopped working on my Windows machine. I updated my config to use forward slashes (`/`) and now everything works again 😌
