### ISSUE TITLE
No support of @client directive

### ISSUE THREAD

**Issue by yairopro** [apollographql/vscode-graphql#60]
![](https://user-images.githubusercontent.com/8110568/156556608-e51eb9b2-bc18-41ab-ba55-4c49c0b8aa6e.png)

**Comment by Fxlr8** [comment]
There is an easy fix for that:

Create a local graphql schema file if you don't have one and add the following line to the beginning:

clientSchema.graphql
```graphql
directive @client on FIELD

```

Then add that client schema to your .graphqlrc.yml like that
```yml
schema:
  - https://some-remote-schema.net/api/graphql
  - clientSchema.graphql # <- here
documents: "src/**/*.{graphql,js,ts,jsx,tsx}"
```

Done

**Comment by yairopro** [comment]
I have no `.graphqlrc.yml`, I use an `apollo.config.js` file. Do you know how to configure it in the same way?

**Comment by almondheng** [comment]
You can configure it like this.
```js
// apollo.config.js

module.exports = {
  client: {
    includes: [ . . . ]
    service: {
      name: '' // YOUR APP NAME,
      localSchemaFile: './path/to/your/local/clientSchema.gql'
    }
  }
}
```
However, it wouldn't solve your problem because even though the `@client` directive can be validated, the field itself is still not recognized due to it not being defined in the schema.

**Comment by phryneas** [comment]
Hi,
I'm sorry for the late answer - I'm sure you solved this in the meantime but I'll answer anyways so other people in the future can find this.

---

The `@client` directive itself is supported, but fields you annotate with `@client` still need to be defined or we will warn you about that.

To do that, you could create a `extendSchemaWithClientFields.js` file somewhere in your workspace with contents like:
```
import gql from "graphql-tag";
gql`
  extend type Shop {
    logoUrl: String
  }
`
```

With that in place, the `logoUrl` field will be available and you will even get warnings if you forget to use the `@client` directive with it.
